language: php

sudo: true

php:
  - 7.1
  - 7.2

env:
  - LARAVEL_VERSION="5.5.*" TESTBENCH_VERSION="3.5.*"
  - LARAVEL_VERSION="5.6.*" TESTBENCH_VERSION="3.6.*"

before_script:
  - composer self-update
  - composer require orchestra/testbench:"$TESTBENCH_VERSION" illuminate/support:"$LARAVEL_VERSION"
  - composer install

script: phpunit --coverage-text